# merged_v4.json -> explorer/build/records_spine.py  (pass 9, corpus 'arch-spine')
# Mints stable kebab ids, resolves memberships against the existing corpus, and emits the
# fact-record module in the exact shape build.py PHASE 1 consumes (see records_proc.py).
import json, os, re, collections

SWE = r'E:\dev\corpora\SWE'
W = os.path.join(SWE, '_spine_work')
OUT = os.path.join(SWE, 'explorer', 'build', 'records_spine.py')

STAGES = ['needs','obligations','requirements','design','tools-process']
DOMAINS = ['complex-scale','complex-science','governance','measurement','runtime-ops','hand-c','model-c']
# harvest type -> build.py TYPE_MAP key
TYPE = {'book':'book', 'standard':'standard', 'paper':'paper', 'tool-doc':'tooling-doc',
        'living-web':'official-doc', 'report':'report', 'other':'other'}

EXISTING = {}
for line in open(os.path.join(W, 'id_index.tsv'), encoding='utf-8').read().splitlines()[1:]:
    p = line.split('\t')
    if len(p) >= 3:
        EXISTING[p[0]] = p[2]

works = json.load(open(os.path.join(W, 'merged_v4.json'), encoding='utf-8'))
THIN = {}
tp = os.path.join(W, 'thin_cells.json')
if os.path.exists(tp):
    THIN = json.load(open(tp, encoding='utf-8'))

log = []

STD = re.compile(r'\b(ISO/IEC/IEEE|ISO/IEC|ISO/SAE|ISO|IEC|IEEE|EN|DO|ARP|NPR|ECSS|UNECE|RTCA|SAE)\s*[-/]?\s*([0-9]{2,6})(?:\s*-\s*([0-9]+))?', re.I)
BODY = {'iso/iec/ieee':'iso', 'iso/iec':'iso', 'iso/sae':'iso', 'iso':'iso', 'iec':'iec', 'ieee':'ieee',
        'en':'en', 'do':'do', 'arp':'arp', 'npr':'npr', 'ecss':'ecss', 'unece':'unece', 'rtca':'do', 'sae':'sae'}

def slug(s, n=22):
    return re.sub(r'[^a-z0-9]', '', (s or '').lower())[:n]

def surname(authors):
    a = re.split(r'[,;&]| and ', authors or '')[0].strip()
    toks = [t for t in re.split(r'\s+', a) if t and not re.fullmatch(r'[A-Z]\.?([A-Z]\.?)*', t)]
    return slug(toks[-1], 14) if toks else ''

def mint(w):
    """A short, stable, readable id — standards by designation, works by author, else by title."""
    hay = (w.get('ident') or '') + ' ' + (w.get('title') or '')
    m = STD.search(hay)
    if m and (w.get('type') == 'standard' or m.group(1).lower() in ('do', 'arp', 'en', 'iec', 'npr')):
        body = BODY.get(m.group(1).lower(), slug(m.group(1), 6))
        return body + m.group(2) + (('-' + m.group(3)) if m.group(3) else '')
    sn = surname(w.get('authors'))
    yr = re.search(r'(19|20)\d{2}', w.get('year') or '')
    if sn and len(sn) > 2:
        return sn + (yr.group(0)[2:] if yr else '')
    t = slug(re.sub(r'^(the|a|an)\s+', '', (w.get('title') or '').lower()), 20)
    return t or 'spine'

def year_of(w):
    y = (w.get('year') or '').strip()
    if re.search(r'living', y, re.I):
        return 'living'
    m = re.search(r'(19|20)\d{2}', y)
    return m.group(0) if m else 'UNRESOLVED'

def joined(vals, allowed):
    return ';'.join([v for v in (vals or []) if v in allowed])

news, mems, used = [], [], set(EXISTING)
promoted = 0
for w in sorted(works, key=lambda x: (x.get('title') or '').lower()):
    st, dm = joined(w.get('stages'), STAGES), joined(w.get('domains'), DOMAINS)
    if not st or not dm:
        log.append('SKIP untagged: %s' % (w.get('title') or '')[:60]); continue
    role = (w.get('role') or 'core').strip() or 'core'
    mid = (w.get('membership_id') or '').strip()
    if mid:
        if mid in EXISTING:
            mems.append((mid, st, dm, role))
        else:
            log.append('SKIP membership to unknown id %s' % mid)
        continue
    mid2 = mint(w)
    if mid2 in EXISTING:
        # the mint collided with a work the corpus already holds — that is a MISSED MEMBERSHIP,
        # not an id clash. Claim it rather than minting a duplicate node.
        log.append('PROMOTED to membership (id collides with existing %s): %s' % (mid2, (w.get('title') or '')[:52]))
        mems.append((mid2, st, dm, role)); promoted += 1; continue
    base, k = mid2, 2
    while mid2 in used:
        mid2 = base + str(k); k += 1
    used.add(mid2)
    news.append((mid2, w, st, dm, role))

# collapse duplicate membership claims, unioning their tags
mm = {}
for mid, st, dm, role in mems:
    if mid not in mm:
        mm[mid] = [set(), set(), set()]
    mm[mid][0].update(st.split(';')); mm[mid][1].update(dm.split(';')); mm[mid][2].update(role.split(';'))

def pystr(s):
    return repr((s or '').replace('\r', ' ').replace('\n', ' ').strip())

L = []
L.append('# -*- coding: utf-8 -*-')
L.append('# GENERATED by _spine_work/tools/gen_records.py — do not hand-edit; regenerate from merged_v4.json.')
L.append('# PHASE 1 fact records — corpus: arch-spine (PASS 9, the architecture spine:')
L.append('# stakeholder needs -> obligations -> architecture requirements -> architecture design -> tools & process).')
L.append('# Source: ../../_spine_work/merged_v4.json (harvested 2026-09-19). Mission: ../../MISSION_arch_spine_v1.md.')
L.append('# Raw tags: stage | domain | role  (each \';\'-joinable).')
L.append('#   stage:  ' + ' | '.join(STAGES))
L.append('#   domain: ' + ' | '.join(DOMAINS))
L.append('#   role:   anchor | core | advanced | survey')
L.append('# Type mapping applied at generation: tool-doc -> tooling-doc, living-web -> official-doc.')
L.append('# Verification: \'verified\' ONLY where a primary/authoritative page was loaded live confirming the')
L.append('# exact identifier, with the confirming snippet recorded in the harvest. A membership grep is NOT')
L.append('# verification — 82 round-1 entries that made that claim were demoted before this file was generated.')
L.append('R = []')
L.append("C = 'arch-spine'")
L.append('')
L.append('')
L.append("def n(id, title, au, yr, typ, stage, domain, role, note='', ident='', ver='verified', unres=()):")
L.append('    """A NEW node this pass grounds (first insertion)."""')
L.append('    R.append(dict(id=id, corpus=C, title=title, authors=au, year=yr, rtype=typ,')
L.append('                  verification=ver, note=note, ident=ident, unresolved=list(unres),')
L.append('                  raw=dict(stage=stage, domain=domain, role=role)))')
L.append('')
L.append('')
L.append('def m(id, stage, domain, role):')
L.append('    """MEMBERSHIP of an EXISTING corpus node — REUSES the exact id; PHASE 1 merges by id."""')
L.append("    R.append(dict(id=id, corpus=C, title='(membership — see home corpus)', authors='',")
L.append("                  year='UNRESOLVED', rtype='other', verification='unverified', note='',")
L.append("                  ident='', unresolved=[], raw=dict(stage=stage, domain=domain, role=role)))")
L.append('')

by_stage = collections.defaultdict(list)
for rec in news:
    by_stage[rec[2].split(';')[0]].append(rec)
L.append('')
L.append('# ' + '=' * 78)
L.append('# NEW NODES — %d works this pass grounds, grouped by primary stage' % len(news))
L.append('# ' + '=' * 78)
for stg in STAGES:
    rows = by_stage.get(stg) or []
    if not rows:
        continue
    L.append('')
    L.append('# ---- stage: %s (%d) ----' % (stg, len(rows)))
    for mid, w, st, dm, role in rows:
        unres = []
        u = (w.get('unresolved') or '').strip()
        if u:
            unres.append(u[:110])
        L.append('n(%s, %s, %s, %s, %s,' % (pystr(mid), pystr(w.get('title')), pystr(w.get('authors')),
                                            pystr(year_of(w)), pystr(TYPE.get(w.get('type'), 'other'))))
        L.append('  %s, %s, %s,' % (pystr(st), pystr(dm), pystr(role)))
        L.append('  note=%s, ident=%s, ver=%s%s)'
                 % (pystr((w.get('note') or '')[:240]), pystr((w.get('ident') or '')[:140]),
                    pystr(w.get('verification') or 'unverified'),
                    (', unres=' + repr(tuple(unres))) if unres else ''))
L.append('')
L.append('')
L.append('# ' + '=' * 78)
L.append('# MEMBERSHIPS — %d works the corpus already holds, now claimed by the spine' % len(mm))
L.append('# ' + '=' * 78)
for mid in sorted(mm):
    st, dm, role = mm[mid]
    L.append('m(%s, %s, %s, %s)  # %s' % (pystr(mid), pystr(';'.join(sorted(st))), pystr(';'.join(sorted(dm))),
                                          pystr(';'.join(sorted(role))), (EXISTING.get(mid) or '')[:58]))
L.append('')
L.append('')
L.append('# Thin-cell adjudications from the adversarial critic panels (round 1 and round 2).')
L.append('# Consumed by build.py PHASE 3 into relations.views.spine.thin, and rendered by views/spine.js.')
L.append('SPINE_THIN = ' + json.dumps(THIN, indent=4, ensure_ascii=False))
L.append('')

open(OUT, 'w', encoding='utf-8').write('\n'.join(L))

ver = sum(1 for _, w, _, _, _ in news if w.get('verification') == 'verified')
print('records_spine.py written to explorer/build/')
print('  new nodes   : %d  (%d verified / %d unverified)' % (len(news), ver, len(news) - ver))
print('  memberships : %d distinct existing corpus ids' % len(mm))
print('  promoted to membership by id collision: %d' % promoted)
print('  thin-cell adjudications carried: %d' % len(THIN))
print('  total pass-9 records: %d' % (len(news) + len(mm)))
if log:
    print('\nnotes (%d):' % len(log))
    for x in log[:20]:
        print('   -', x)
